### ISSUE TITLE
Add ReliableNetcode.NET to your benchmark

### ISSUE THREAD

**Issue by Wizzard033** [nxrighthere/BenchmarkNet#1]
Just saw this library and was wondering how it stacked up versus ENet...

https://github.com/KillaMaaki/Netcode.IO.NET
https://github.com/KillaMaaki/ReliableNetcode.NET

**Comment by nxrighthere** [comment]
I already tried and, unfortunately, this implementation is not performing well. More information is [here](https://forum.unity.com/threads/benchmarknet-stress-test-for-enet-unet-litenetlib-lidgren-miniudp-hazel-photon-and-neutrino.512507/page-2#post-3365230).

**Comment by Wizzard033** [comment]
Thanks for the info! I really appreciate these benchmarks.

**Comment by nxrighthere** [comment]
Thank you.
