### ISSUE TITLE
Clarification on throughput numbers

### ISSUE THREAD

**Issue by paulie-g** [nxrighthere/BenchmarkNet#10]
Cheers for doing this work. I've got two questions:
* Are you measuring throughput in MB/s or mb/s (MegaBytes/s or Megabits/s)?
* Is this the maximum throughput or the throughput given the workload? In other words, is the throughput limited by the implementation or the amount of packets you send?

**Comment by nxrighthere** [comment]
Greetings, thank you.

> Are you measuring throughput in MB/s or mb/s (MegaBytes/s or Megabits/s)?

In the application, we have _payload throughput_ which is measured in mbps -> megabits per second. Payload throughput means how much data the server is sending and receiving. It does not include any overhead of the packets. So, to measure the total bandwidth (that you see on the results page), I'm using an external application to capture everything at the IP level in MB -> megabytes (total captured amount of data for the server instance).

> Is this the maximum throughput or the throughput given the workload? In other words, is the throughput limited by the implementation or the amount of packets you send?

For example, let's say that we have: _Payload throughput: 25,06 mbps \ 46,08 mbps_. The first value means how much data the server should send and receive _right now_. The second value means a total possible throughput based on the current setup (clients count, message length, and send rate).
