### ISSUE TITLE
Telepathy Mirror Integration

### ISSUE THREAD

**Issue by friuns2** [nxrighthere/BenchmarkNet#13]
looks like very rapidly growing project, i wonder how good benchmarks it will show because their default configuration is for TCP

https://github.com/vis2k/Mirror

**Comment by nxrighthere** [comment]
An answer is [here](https://forum.unity.com/threads/benchmarknet-stress-test-for-enet-unet-litenetlib-lidgren-miniudp-hazel-photon-and-others.512507/page-6#post-3823210).
