### ISSUE TITLE
Add more network libraries?

### ISSUE THREAD

**Issue by Krakean** [nxrighthere/BenchmarkNet#18]
@nxrighthere Hello
https://github.com/MarkioE/Networker - can you also please add this library to results table?

**Comment by nxrighthere** [comment]
Sure, why not.

**Comment by nxrighthere** [comment]
I'm unable to build it for .NET Framework unfortunately the library [doesn't support](https://github.com/MarkioE/Networker/blob/master/Networker/Networker.csproj) it as a [target framework](https://docs.microsoft.com/en-us/dotnet/standard/frameworks).
