### ISSUE TITLE
More network.

### ISSUE THREAD

**Issue by jclitwin** [nxrighthere/BenchmarkNet#19]
Yo nxrighthere,

It's possible to integrate RakNet/SLikeNet in your benchmark?

Cheers!

**Comment by nxrighthere** [comment]
https://github.com/nxrighthere/BenchmarkNet/issues/2

**Comment by jclitwin** [comment]
Sorry, I forgot to check if there was another issue about RakNet. Have you checked the other RakNet fork (SLikeNET)?

I have questions regarding the ENET or RakNet. As I always see your opinions (especially in the Unity 3D forum), you have a sense of criticism/opinions and discussions about networking ideas, so you have a lot of experience with Network.

Would you recommend me to use ENET or RakNet?

**Comment by nxrighthere** [comment]
> Have you checked the other RakNet fork (SLikeNET)?

No, I didn't try it, but I'm [aware](https://forum.unity.com/threads/what-is-the-best-networking-solution-for-a-game-like-rust-mmo.463018/#post-3681784) of this fork, and I'm not interested really. It doesn't look fundamentally different from the original version except that it much heavier.

> Would you recommend me to use ENET or RakNet (in a situation in which P2P will not be used, will be used server (RoomServer) in which it will process players in a match (around 2K to 3K of online players simultaneously)?

With this amount of concurrent players, you need a proper workload distribution/bandwidth optimization strategies in first place. If you understand what you aim for, and you have an idea of how it should be done right, then ENet is ready to serve as a reliable transport for it except that it doesn't provide any secure communication between endpoints.
