### ISSUE TITLE
Neutrino integration

### ISSUE THREAD

**Issue by aienabled** [nxrighthere/BenchmarkNet#4]
I wanted to ensure that the latest Neutrino version is used and that it's built as `RELEASE`, but turns out the source code is different.

Have you actually built it from the source code?
If so, where you've got the Neutrino source code?
Otherwise, where you've got the `Neutrino.dll` you're using in the latest 1.09 release?

Here https://github.com/nxrighthere/BenchmarkNet/blob/b64570442006301f5c4549b6593879de03483bae/BenchmarkNet.cs#L48 the link leads to https://github.com/Claytonious/Neutrino which is supposedly the origin of the source code. But it was not updated for the last year (no commits, no branches, no releases) while your benchmark 1.09 version was built 3 months ago.
If I build Neutrino from there, I got `NeutrinoCore.dll` and `msgpack.dll` (which both are required for the benchmark to function) - not a single `Neutrino.dll` (which includes msgpack sources) as used in this repo in [the latest 1.09 release](https://github.com/nxrighthere/BenchmarkNet/releases/tag/1.09).

Even worse, after integrating `NeutrinoCore.dll` and `msgpack.dll` into the benchmark, it doesn't perform correctly - it crashes after some time with an exception inside Neutrino:
`NTO Error: Error handling message: System.InvalidOperationException: EndReceiveFrom can only be called once for each asynchronous operation.
   at System.Net.Sockets.Socket.EndReceiveFrom(IAsyncResult asyncResult, EndPoint& endPoint)
   at Neutrino.Core.Node.HandleMessageReceived(IAsyncResult result)`
Screenshot:
![screenshot at 11-35-19](https://user-images.githubusercontent.com/865384/42672543-d28f7c84-8690-11e8-8863-b5bb7988ad22.jpg)

Regards!

**Comment by nxrighthere** [comment]
All .NET libraries are built with Roslyn from the source code. Prebuilt libraries are not used in the application.

**Comment by aienabled** [comment]
@nxrighthere, thanks!
So you have merged msgpack and Neutrino sources into a single DLL with Roslyn compiler?
But why? Did you wanted to ensure there are no conflicts with msgpack from other networking libraries? I've checked all the .NET assemblies and none of them except Neutrino are using msgpack so there could not be any conflicts.

Can you provide the link on the actual source code (a link to the commit) you have used to build Neutrino from? And, ideally, a build script for the compiler which produced `Neutrino.dll`.
With the latest version from `master` branch from https://github.com/Claytonious/Neutrino it doesn't work to me with the exceptions I've reported above; and that version is quite old (May 31, 2017) so I'm curious which version you might have used as it works fine with your `Neutrino.dll`.

It's necessary so we can also build it (and ensure we're using the `RELEASE` version so the results are correct). Some developers might want to tweak the source code to optimize it by using your benchmark as the measurements provider for their performance research. So it's important to include the actual links on the actual commits you have used - especially if it was your fork of a library.

Regards!

**Comment by nxrighthere** [comment]
> So you have merged msgpack and Neutrino sources into a single DLL with Roslyn compiler?
But why? Did you wanted to ensure there are no conflicts with msgpack from other networking libraries? I've checked all the .NET assemblies and none of them except Neutrino are using msgpack so there could not be any conflicts.

Yes, both are merged into single DLL. This is done simply for convenience because there are too many libraries shipped with the application.

> Can you provide the link on the actual source code (a link to the commit) you have used to build Neutrino from? And, ideally, a build script for the compiler which produced Neutrino.dll.
With the latest version from master branch from https://github.com/Claytonious/Neutrino it doesn't work to me with the exceptions I've reported above; and that version is quite old (May 31, 2017) so I'm curious which version you might have used as it works fine with your Neutrino.dll.

It's the latest version from the master branch. There is nothing special, source code is compiled with the Roslyn.

> It's necessary so we can also build it (and ensure we're using the RELEASE version so the results are correct). Some developers might want to tweak the source code to optimize it by using your benchmark as the measurements provider for their performance research. So it's important to include the actual links on the actual commits you have used - especially if it was your fork of a library.

Not a single line of code has been changed by me.

**Comment by aienabled** [comment]
@nxrighthere, understood, thanks.
I have an exception which I've reported in Neutrino repo. For some reason this exception is not reproducible with your `Neutrino.dll` which led me to the conclusion there are at least some binary difference or maybe even the source code difference.
I hope the developer of Neutrino will look what's wrong.

**Comment by nxrighthere** [comment]
Ah... I completely forgot about [this](https://github.com/Claytonious/Neutrino/issues/2) exception. Yes, I'm using a [stub](https://github.com/Claytonious/Neutrino/issues/1) to suppress it.
