### ISSUE TITLE
LiteNetLib integration

### ISSUE THREAD

**Issue by aienabled** [nxrighthere/BenchmarkNet#5]
(yes, I know it will sound the same as https://github.com/nxrighthere/BenchmarkNet/issues/4 sorry, but here we go)
I wanted to ensure that the latest LiteNetLib version is used and that it's built as `RELEASE`, but turns out the source code is different.

Have you actually built it from the source code?
If so, where you've got the LiteNetLib source code?
Otherwise, where you've got the LiteNetLib.dll you're using in the latest 1.09 release?

Here
https://github.com/nxrighthere/BenchmarkNet/blob/b64570442006301f5c4549b6593879de03483bae/BenchmarkNet.cs#L36
the link leads to https://github.com/RevenantX/LiteNetLib where the source code, two branches and multiple releases are available. However, I cannot make it run with either the latest source code or with any release for the past year.
The [BenchmarkNet 1.09 release](https://github.com/nxrighthere/BenchmarkNet/releases/tag/1.09) was uploaded 3 months ago so I assume you might have used a fresh version but none of the latest release or source code is compatible): even an almost 1 year old LiteNetLib 0.7.6 (release from Oct 8, 2017) is not compatible with this benchmark as API is different - the `LiteNetLib.NetManager` constructor doesn't accept `maxClients` parameter.

I've tried to integrate latest [LiteNetLib 0.7.7.2](https://github.com/RevenantX/LiteNetLib/releases/tag/0.7.7.2) but API is different (more than 12 errors, mostly - different constructor signature, no `ConnectionRequestEvent` event, different `NetworkReceiveEvent` delegate signature).

So, I've updated BenchmarkNet to work with the latest LiteNetLib built from the source code from master branch (which was updated recently). The only required API change was to remove `maxClients` parameter from `new NetManager(listener, maxClients)`) constructor.
But it doesn't work properly - not all the clients are connecting and in the result it fails with "Overload" state. Screenshot:
![screenshot at 12-02-11](https://user-images.githubusercontent.com/865384/42673249-9d267292-8694-11e8-8fb0-6aef7f0c9fe6.jpg)

How I can build a compatible version of `LiteNetLib` which will work properly in this benchmark?

Regards!

**Comment by nxrighthere** [comment]
The latest compatible LiteNetLib version with the application is 0.7.7.1. You can built the library from the [this](https://github.com/RevenantX/LiteNetLib/tree/0.7.7.1) tree.

**Comment by aienabled** [comment]
@nxrighthere, yes, I've tried it, but it's not compatible. The API is different:

- [NetManager](https://github.com/RevenantX/LiteNetLib/blob/0.7.7.1/LiteNetLib/NetManager.cs) doesn't have a constructor which is used in [your source code here](https://github.com/nxrighthere/BenchmarkNet/blob/b64570442006301f5c4549b6593879de03483bae/BenchmarkNet.cs#L790) 
- also you use [event here](https://github.com/nxrighthere/BenchmarkNet/blob/b64570442006301f5c4549b6593879de03483bae/BenchmarkNet.cs#L795) which is not defined in that `NetManager.cs` (only `PeerConnectedEvent` event is defined there).
- and signature of the callback in [your source here](https://github.com/nxrighthere/BenchmarkNet/blob/b64570442006301f5c4549b6593879de03483bae/BenchmarkNet.cs#L799) doesn't match [the according delegate signature from LiteNetLib](https://github.com/RevenantX/LiteNetLib/blob/0.7.7.1/LiteNetLib/INetEventListener.cs#L76)

It seems you have used a different version.

**Comment by nxrighthere** [comment]
Yea, it seems that some code has changed in this tree since the last time when I updated the library on my side. I'll update it to the latest version as soon as I can.

**Comment by aienabled** [comment]
@nxrighthere, thanks. You can also point on the particular commit you've compiled the source from (if you still have the pulled repo somewhere on your disk).
It's essential for us in order to perform the further measurements. I want to be very sure that only the `RELEASE` versions are used for all the libraries and, ideally, that everything is compiled straight from the fresh and actual source code.

**Comment by RevenantX** [comment]
@aienabled @nxrighthere there was version from master (0.8.x) which more optimized than stable version.

**Comment by nxrighthere** [comment]
I've updated `BenchmarkNet.cs` to make it compatible with the latest LiteNetLib version. 

@aienabled Please, build the library with defined `DISABLE_IPV6` directive to avoid some performance issues that related to IPv6 threads.
