### ISSUE TITLE
Add TNET to the list?

### ISSUE THREAD

**Issue by SoftwareGuy** [nxrighthere/BenchmarkNet#6]
TNET is not an open source solution (it's paid) but it's advertised as a replacement for UNET as long as you get familiar with how it operates.

Is there any chance that we could add this to the benchmark? It's touted to be the better networking solution... but it really needs to be put under the hammer (the devs say the dedicated server instance can run fine with 1000 connections on a R-Pi under 100MB of RAM apparently).

**Comment by nxrighthere** [comment]
If TNet can work as a standalone server/client outside of the Unity environment and if I get a copy of it, no problem, I'll try to integrate it with the application.

**Comment by SoftwareGuy** [comment]
I could supply you with the version I have... what would be the best way of contacting you (unless you want to shoot me an email or GitHub message)?

**Comment by nxrighthere** [comment]
Just send an [email](mailto:nxrighthere@gmail.com) would be nice.

**Comment by nxrighthere** [comment]
I looked into the source code, and the good news is that the server can work as a standalone application, but the client can't be compiled outside of the Unity environment, unfortunately. It's tightly integrated with Unity API, so I can't use it in the application.

**Comment by SoftwareGuy** [comment]
Bugger. That's a shame, at least it was worth the gamble. Will keep an eye on this project though, I honestly do believe having solid (independent) figures to back up network server claims is really handy - and will help back up any false advertising, for example, when a network layer claims to be the most memory efficient when it's actually a mess.
