### ISSUE TITLE
NetworkComms

### ISSUE THREAD

**Issue by Adevien** [nxrighthere/BenchmarkNet#7]
Hi, could you add in future a benchmark for NetworkCommsDotNet ? Apreciated.

**Comment by nxrighthere** [comment]
Greetings. When the application was in development, I tried to integrate NetworkComms into it. I ran into some issues and postponed the integration. I'll try one more time to do this, but only when I have time. I'm just busy these days...

**Comment by Adevien** [comment]
Thanks.

**Comment by nxrighthere** [comment]
It still doesn't work for me. And [this](https://github.com/MarcFletcher/NetworkComms.Net/issues/25) problem tells _don't build your stuff on top of dead projects_.
