### ISSUE TITLE
Maybe add Forge Networking to the list?

### ISSUE THREAD

**Issue by SoftwareGuy** [nxrighthere/BenchmarkNet#8]
Here's another worthy candidate for the list. Can you take a look and consider adding it to your list of benchmarks if you are able to?

**What:** Forge Networking
**URL:** https://github.com/BeardedManStudios/ForgeNetworkingRemastered

Claims to be "the best bandwidth-wise" but without solid benchmarks that's probably just marketing fluff.

**Comment by nxrighthere** [comment]
It was [requested](https://forum.unity.com/threads/benchmarknet-stress-test-for-enet-unet-litenetlib-lidgren-miniudp-hazel-photon-and-others.512507/#post-3354806) a long time ago. A problem that prevents integration is described [here](https://github.com/BeardedManStudios/ForgeNetworkingRemastered/issues/126). I had a talk with Forge developer in those days, but it did not lead to anything as you can see.

**Comment by SoftwareGuy** [comment]
RIP. That's a really shitty outcome, but I guess it happens.
